@extends('layouts.app')
@section('content')
<h1 class="h3">{{ $section ? 'Ubah' : 'Tambah' }} Jadwal Kelas</h1><form method="post" action="{{ $section ? route('sections.update',$section) : route('sections.store') }}" class="card card-body">@csrf @if($section)@method('PUT')@endif
<select class="form-select mb-3" name="period_id">@foreach($periods as $item)<option value="{{ $item->id }}" @selected(old('period_id',$section?->period_id)==$item->id)>{{ $item->name }}</option>@endforeach</select>
<select class="form-select mb-3" name="course_id">@foreach($courses as $item)<option value="{{ $item->id }}" @selected(old('course_id',$section?->course_id)==$item->id)>{{ $item->code }} — {{ $item->name }}</option>@endforeach</select>
<select class="form-select mb-3" name="lecturer_nik" id="lecturer"><option value="">Dosen belum terdata / lainnya</option>@foreach($lecturers as $item)<option value="{{ $item->nik }}" @selected(old('lecturer_nik',$section?->lecturer_nik)==$item->nik)>{{ $item->name }}</option>@endforeach</select><input class="form-control mb-3" id="presenter" name="presenter_name" value="{{ old('presenter_name',$section?->presenter_name) }}" placeholder="Nama dosen/pemateri lainnya">
<select class="form-select mb-3" name="room_id">@foreach($rooms as $item)<option value="{{ $item->id }}" @selected(old('room_id',$section?->room_id)==$item->id)>{{ $item->code }}</option>@endforeach</select><input class="form-control mb-3" name="class_code" value="{{ old('class_code',$section?->class_code) }}" placeholder="Kode kelas (opsional)"><input class="form-control mb-3" name="class_type" value="{{ old('class_type',$section?->class_type) }}" placeholder="Jenis kelas (opsional)">
<select class="form-select mb-3" name="day_of_week">@foreach(['Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'] as $i=>$day)<option value="{{ $i+1 }}" @selected(old('day_of_week',$section?->day_of_week)==$i+1)>{{ $day }}</option>@endforeach</select>
@foreach(['start_time'=>'Jam mulai','end_time'=>'Jam selesai'] as $field=>$label)<select class="form-select mb-3" name="{{ $field }}"><option value="">{{ $label }}</option>@for($hour=7;$hour<=22;$hour++)@foreach([0,30] as $minute)@php($time=sprintf('%02d:%02d',$hour,$minute))<option value="{{ $time }}" @selected(old($field,substr($section?->$field ?? '',0,5))===$time)>{{ $time }}</option>@endforeach@endfor</select>@endforeach<button class="btn btn-primary">Simpan</button></form><script>const lecturer=document.querySelector('#lecturer'),presenter=document.querySelector('#presenter');function toggle(){presenter.disabled=lecturer.value!=='';if(lecturer.value)presenter.value=''}lecturer.addEventListener('change',toggle);toggle();</script>@endsection
